[0m18:51:26.968998 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000024560EFF4A0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002455E8D9190>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000024560EFCFB0>]}


============================== 18:51:26.999859 | f5e57309-d0bb-449a-813d-862415286ed3 ==============================
[0m18:51:26.999859 [info ] [MainThread]: Running with dbt=1.9.4
[0m18:51:27.002823 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\Mari√©ta\\.dbt', 'debug': 'False', 'warn_error': 'None', 'log_path': 'logs', 'fail_fast': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'invocation_command': 'dbt test --select +stg_ventes', 'log_format': 'default', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m18:51:27.005823 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\Mari√©ta\Desktop\bookshop\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m18:51:27.009823 [debug] [MainThread]: Command `dbt test` failed at 18:51:27.008824 after 0.43 seconds
[0m18:51:27.012338 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002455DAC0C80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002455E8D9190>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000024560D49A30>]}
[0m18:51:27.013361 [debug] [MainThread]: Flushing usage events
[0m18:51:27.860732 [debug] [MainThread]: An error was encountered while trying to flush usage events
